### ISSUE TITLE
Got a syntax error  when ran on Win Server 2019 standard

### ISSUE THREAD

**Issue by mittu80** [enthought/comtypes#500] opened 2023-12-14 15:08 UTC
Hello, 

I tried to import module  pywifi and its dependancy comtypes but got the following syntax error.
__init__.py line 381
![image](https://github.com/enthought/comtypes/assets/84013619/23010a8d-0831-4d93-9f4f-eff05f4c3e64)

Can you help me fix this?

**Comment by junkmd** [comment] 2023-12-17 13:45
Hi,

I think that the `comtypes` in your environment is a quite old version from the time when it supported Python 2.6.
By executing `pip install -U comtypes`, you can update to the current version that natively supports Python 3.x.

**Comment by mittu80** [comment] 2023-12-18 07:25
Hi, 
Thanks for your answer. I've tried the latest 1.2.0 as well unfortunately i received a a ctypes DLL Load error.
I am suspecting the latest rel is not compatible to windows server (virtual pc) as when i ran on windows laptop it worked.

**Comment by junkmd** [comment] 2023-12-18 12:34
Hi,

> I might be wrong here as in mycase its win server and not win CE.

I think that's probably the case.
One of the virtual environments I use for my main job is Windows Server, and `comtypes` is functioning on it.

> I've tried the latest 1.2.0 as well unfortunately i received a ctypes DLL Load error while using pywifi/_wifiutil_win.py (pls see the below pic) ![image](https://private-user-images.githubusercontent.com/84013619/291188272-6567a7fe-2848-4b06-85ae-9b55c1c16ed6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI5MDIxNzIsIm5iZiI6MTcwMjkwMTg3MiwicGF0aCI6Ii84NDAxMzYxOS8yOTExODgyNzItNjU2N2E3ZmUtMjg0OC00YjA2LTg1YWUtOWI1NWMxYzE2ZWQ2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE4VDEyMTc1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJiYWUwNGE0M2ZlYjI3ZDc4YjBiZmQzNThjZjM1ODg2YThiOWIzMTY1ODMzNzViMmIzNTQxNGZiMTk4NjJmMzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.wtlP4ZqAzN-pRSmxNE-mKGZlLtgxy8p14GB1DxPStKg)
> 
> I am suspecting the latest rel is not compatible to windows server (virtual pc) as when i ran the same on windows laptop it worked.

It seems that the absence of `wlanapi.dll` in your environment is the cause of the error.
https://github.com/awkman/pywifi/blob/719baf73d8d32c623dbaf5e9de5d973face152a4/pywifi/_wifiutil_win.py#L39
https://docs.python.org/3/library/ctypes.html#ctypes.WinDLL
https://docs.python.org/3/library/ctypes.html#ctypes.LibraryLoader

I googled "wlanapi.dll windows server 2019", and it appears that the absence of wlanapi.dll is a universal issue on Windows Server 2019.
https://www.google.com/search?q=wlanapi.dll+windows+server+2019

> another Q: is there any workaround for using the comtypes also on raspberry pi devices(Linux) ? along with windows?

Since COM is specific to Windows, it cannot be used on other OS. Please refer to https://github.com/enthought/comtypes/issues/479#issuecomment-1550658623.

It seems that the error was not caused by the latest release version of comtypes, so I will close this issue.
If you have any questions other than the error handling syntax, please create another issue.

**Closed by junkmd** 2023-12-18 12:34 UTC
Labels: shared_info

**Comment by vasily-v-ryabov** [comment] 2024-01-01 19:32
Yes, `wlanapi.dll` is used by `pywifi` package and its absence should be checked by `pywifi`. Also `windll` is a Windows-specific part of built-in package `ctypes`, not `comtypes`. So even in this aspect `comtypes` is not directly involved. But it could be not easily recognizable so you're welcome to get help here if you're in doubt.
