### ISSUE TITLE
PumpEvents didn't work while PumpWaitingMessages was fine

### ISSUE THREAD

**Issue by be4pro** [enthought/comtypes#159] opened 2018-07-22 07:06 UTC
```
from comtypes.client import CreateObject
import comtypes.gen.someCOM as AA
BB = CreateObject(AA.someLib)

class someLibEvents:
    def OnSth(self):
        print("message")

from comtypes.client import GetEvents
theEvent = someLibEvents()
theEventHandler = GetEvents(BB, theEvent)
```

`pythoncom.PumpWaitingMessages()` prints "message" as expected at some point

`PumpEvents(30)` shows as below
Traceback (most recent call last):
  File ".\run_xx.py", line 59, in <module>
    PumpEvents(30)
  File "D:\Python\site-packages\comtypes\client\_events.py", line 277, in PumpEvents
    ctypes.byref(ctypes.c_ulong()))
  File "_ctypes/callproc.c", line 918, in GetResult
OSError: [WinError -2147417835]

**Comment by jcsteh** [comment] 2020-03-31 19:02
Duplicate of #138. Fixed in #187 (merged).

**Closed** 2020-12-25 12:34 UTC
