### ISSUE TITLE
root.FindAll is too slow

### ISSUE THREAD

**Issue by SpeakSugar** [enthought/comtypes#511] opened 2024-02-06 07:07 UTC
Environment:
```
Python 3.7.0
comtypes 1.3.0
Microsoft Windows [Version 10.0.19045.3930]
```

code
```python
from pywinauto.uia_element_info import UIAElementInfo
import comtypes
import comtypes.client
from comtypes import COMError
from pywinauto import Desktop
import time

if __name__ == '__main__':
    startTime = time.time()
    UIA_dll = comtypes.client.GetModule('UIAutomationCore.dll')
    ui_automation_client = comtypes.gen.UIAutomationClient
    iuia = comtypes.CoCreateInstance(
        ui_automation_client.CUIAutomation().IPersist_GetClassID(),
        interface=ui_automation_client.IUIAutomation,
        clsctx=comtypes.CLSCTX_INPROC_SERVER
    )
    root = iuia.GetRootElement()
    true_condition = iuia.CreateTrueCondition()
    conds = []
    ptrs_array = root.FindAll(UIA_dll.TreeScope_Children, true_condition)

    elements = []
    for n in range(ptrs_array.Length):
        try:
            elements.append(UIAElementInfo(ptrs_array.GetElement(n), False))
        except COMError:
            continue
    backend = Desktop(backend="uia").backend

    for ele in elements:
        print(backend.generic_wrapper_class(ele).window_text())
    print("function usedTime: ", time.time() - startTime)
```
the function usedTime is more than 90s

**Comment by junkmd** [comment] 2024-02-06 10:58
`UIAutomation` tends to slow down processing speed when multiple screens are open.
Additionally, it seems that one-time glitches can be triggered by Windows Update.
Please refer to the following.
https://github.com/pywinauto/pywinauto/issues/1350

After some time has passed, please try running the same script again and let us know if there are any changes.

**Comment by SpeakSugar** [comment] 2024-02-07 01:44
thanks, i will try it

**Comment by junkmd** [comment] 2024-02-09 20:58
A newer Windows 10 build is being released after `19045.3930`.

https://learn.microsoft.com/en-us/windows/release-health/release-information

Have you tried it?

**Comment by SpeakSugar** [comment] 2024-02-21 07:28
windows version update can't resolve this issue.
i find it take slow when i login my electron app.
![D7CA32F560B4F3D5BEA7D39BD733851F](https://github.com/enthought/comtypes/assets/42370088/c2dccfa0-8a0d-4f37-b1ac-e68e20b6fbfa)
when i login, it will take 60s to exec root.findAll

**Comment by junkmd** [comment] 2024-02-23 00:05
> the function usedTime is more than 90s
https://github.com/enthought/comtypes/issues/511#issue-2120105726

> it will take 60s to exec root.findAll
https://github.com/enthought/comtypes/issues/511#issuecomment-1956041944

On a positive note, we can say that it is now 30 seconds faster.

I speculate that the cause of this might be the poor compatibility between your Electron app and UIAutomation.

In other words, I think the cause of this slowness is not related to `comtypes`, `pywinauto`, or Python.

`root.FindAll` speed is affected by the number of open windows. If you provide a more refined condition, it might speed up the processing.

`comtypes` uses the COM library of the execution environment, and that COM library depends on elements of another execution environment.
Therefore, please be aware that `comtypes` may not be the cause, and there could be other factors to consider.

**Comment by SpeakSugar** [comment] 2024-02-23 08:07
Thank you, but I'm quite puzzled about how an electron app is associated with UIAutomation. Do you have any thoughts on this?

**Comment by junkmd** [comment] 2024-02-26 14:23
I have some ideas.
However, I believe that falls within the realm of `pywinauto` even though it indirectly manipulates `comtypes`.

I don't think it's possible to speed up `root.FindAll` by modifying the implementation of `comtypes`.
Therefore, I suggest closing this issue, and instead, opening a new discussion or issue on the `pywinauto` side to explore ways to associate with Electron app more effectively.

**Closed** 2024-02-27 04:09 UTC
